services:
  doorctl-web:
    build: .
    ports:
      - "8800:80"
    restart: unless-stopped
    volumes:
      - ".:/code"
  doorctl-redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379"
